### ISSUE TITLE
Migration script is failing

### ISSUE THREAD

**Issue by ValentinH** [fkanout/users-api-microservice#1]
Hello 👋 

While following the "Getting started" procedure, I get an error at the `npx knex migrate:latest` step: 
![image](https://user-images.githubusercontent.com/2678610/101373475-4569ee80-38ad-11eb-9e10-f748e30d1c73.png)

Do you know what am I doing wrong?

**Comment by fkanout** [comment]
hey @ValentinH !

First, thank you for your time opening the issue 👍🏻 

Unfortunately, I couldn't reproduce it, maybe more info could help, e.g. node version, typescript version, did you imported the environment variables from https://gist.github.com/fkanout/3c537634e88e4972c8e76283bbb1939c?

However, I added the required function that the error message asked for. 

Please give the master branch a `pull` and try again.  And I'm sorry for any inconvenience 😊

**PS:** as mentioned in the README, this command is required only to create the `user`   table. So if you use the config in the gist, you can bypass this step.

cc: @yns01

**Comment by ValentinH** [comment]
I guess the issue comes from the fact that I didn't get the gist 🙈
Was @yns01 supposed to send it to me? 😅

**Comment by fkanout** [comment]
@ValentinH 👍 , and regarding you getting the gist, I will let @yns01 answer it 😉 (🤐 yes)

**Comment by yns01** [comment]
Apologies, forgot to forward you the gist. Here you go @ValentinH  https://gist.github.com/fkanout/3c537634e88e4972c8e76283bbb1939c

**Comment by ValentinH** [comment]
It works fine with the .env file. 👍
